-- -----------------------------------------------------------------
-- Chat script source tracking + live-chat import support
-- -----------------------------------------------------------------
-- Lets the host tell manually-authored script lines apart from lines
-- imported from a real live chat transcript or generated by AI, so the
-- editor UI can show provenance badges and the AI generator can be
-- distinguished from manual edits in analytics later.

create type public.chat_script_source as enum ('manual', 'imported', 'ai');

alter table public.webinar_chat_scripts
  add column if not exists source public.chat_script_source not null default 'manual';

comment on column public.webinar_chat_scripts.source is 'How this script line was created: manual (typed by host), imported (copied from a real live chat transcript), or ai (generated by the AI assistant).';
